seed: 42
device: cuda:1
output_dir: ./outputs/resnet18/baseline_v2_cv

data_root: /mnt/sharedata/ssd_large/users/liyx/kaggle/meteorite-identification
train_csv: train_labels.csv
train_image_dir: train_images
test_image_dir: test_images
sample_submission_path: sample_submission.csv

num_classes: 2
image_size: 224
batch_size: 32
num_workers: 4
pin_memory: true
val_ratio: 0.1

model:
  name: resnet18  # option: resnet18, resnet50, efficientnet_b0, efficientnet_b1
  pretrained: false
  pretrained_path: /mnt/sharedata/ssd_large/users/liyx/kaggle/meteorite-identification/weights/resnet18-f37072fd.pth  # option: resnet18-f37072fd.pth, resnet50-0676ba61.pth
  dropout: 0.2

loss:
  name: cross_entropy
  label_smoothing: 0.05

optimizer:
  name: adamw
  lr: 0.0002
  weight_decay: 0.0003

scheduler:
  name: cosine
  t_max: 30
  lr_min: 1.0e-6

train:
  epochs: 30
  early_stopping_patience: 10
  monitor: f1

cv:
  enabled: false
  n_folds: 5
  stratified: true
  shuffle: true
  seed: 42
  fold: -1  # -1 means run all folds

prediction:
  threshold: 0.5
  aggregation: mean
  # Optional. If empty, test.py will auto-resolve from --exp:
  # - fold_*/best_model.pt (CV ensemble) or
  # - best_model.pt (single model)
  # For manual control, define each source below.
  sources: []
  # sources:
  #   - model_name: resnet50
  #     checkpoint_path: ./outputs/resnet50/baseline/fold_0/best_model.pt
  #     fold: 0
  #     seed: 42
  #     weight: 1.0
  #   - model_name: resnet50
  #     checkpoint_path: ./outputs/resnet50/baseline/fold_1/best_model.pt
  #     fold: 1
  #     seed: 42
  #     weight: 1.0

aug:
  train_rrc_scale_min: 0.55
  train_rrc_scale_max: 1.0
  train_flip_p: 0.5
  train_rotation: 20
  train_jitter_brightness: 0.2
  train_jitter_contrast: 0.2
  train_jitter_saturation: 0.2
  train_jitter_hue: 0.03
  train_erasing_p: 0
  train_erasing_scale_min: 0.02
  train_erasing_scale_max: 0.2
  train_erasing_ratio_min: 0.3
  train_erasing_ratio_max: 3.3
  eval_resize_size: 256
